name: Semgrep

on:
  push:
    branches: ["master"]
  schedule:
    - cron: '20 17 * * *'

jobs:
  semgrep:
    name: semgrep/ci 
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v3
      # Run the "semgrep ci" command on the command line of the docker image.
      - run: semgrep ci --sarif --output=semgrep.sarif || true
        env:
           SEMGREP_RULES: p/default # more at semgrep.dev/explore

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()